name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: ImageMagick action
        uses: jruipinto/ImageMagick-action@v1
        with:
            command: convert -version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./run
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            dest/
