name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: ImageMagick action
        uses: jruipinto/ImageMagick-action@v1
        with:
          command: convert -version
           
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: bash ./run

      - name: Create zip
        run: zip -r icons-${{ github.ref_name }}.zip README.md LICENSE.txt dest

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          prerelease: false
          title: "Release ${{ github.ref_name }}"
          files: |
            LICENSE.txt
            icons-${{ github.ref_name }}.zip
